crm_s9/urls.py
from django.conf.urls import url
from django.contrib import admin
from stark.service.stark import site
from crm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stark/', site.urls),
    url(r'^login/', views.login),
]

crm/models.py
from django.db import models
from rbac.models import *
# Create your models here.
class Department(models.Model):#部门表
    title=models.CharField(verbose_name="部门名称",max_length=16)
    code=models.IntegerField(verbose_name="部门编号",unique=True,null=False)

    def __str__(self):
        return self.title

class UserInfo(models.Model):#员工表
    name=models.CharField(verbose_name="员工姓名",max_length=16)
    username=models.CharField(verbose_name="用户名",max_length=32)
    password=models.CharField(verbose_name="密码",max_length=64)
    email=models.EmailField(verbose_name="邮箱",max_length=64)
    depart=models.ForeignKey(verbose_name="部门",to="Department",to_field="code",on_delete=models.CASCADE)
    user = models.OneToOneField(to=User,null=True)
    def __str__(self):
        return self.name

class Course(models.Model):#课程表
    name=models.CharField(verbose_name="课程名称",max_length=32)

    def __str__(self):
        return self.name

class School(models.Model):#校区表
    title=models.CharField(verbose_name="校区名称",max_length=32)

    def __str__(self):
        return self.title

class ClassList(models.Model):#班级表
    school=models.ForeignKey(verbose_name="校区",to="School",on_delete=models.CASCADE)
    course=models.ForeignKey(verbose_name="课程名称",to="Course",on_delete=models.CASCADE)
    semester=models.IntegerField(verbose_name="班级(期)")
    price=models.IntegerField(verbose_name="学费")
    start_date=models.DateField(verbose_name="开班日期")
    graduate_date=models.DateField(verbose_name="结业日期",null=True,blank=True)
    memo=models.CharField(verbose_name="说明",max_length=256,blank=True,null=True)
    teachers=models.ManyToManyField(verbose_name="任课老师",to="UserInfo",related_name="abc",limit_choices_to={"depart__in":[1002,1005]})  # limit_choices_to 过滤数据  相当于objects.filter(depart__in=)
    #teachers=models.ManyToManyField(verbose_name="任课老师",to="UserInfo",limit_choices_to={'depart_id__in':[1003,1004],})
    tutor=models.ForeignKey(verbose_name="班主任",to="UserInfo",related_name="classes",limit_choices_to={"depart":1001},on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.course.name}({self.semester}期)"

class Customer(models.Model):#客户表
        qq=models.CharField(verbose_name="QQ",max_length=64,unique=True,help_text="QQ号必须唯一")
        name=models.CharField(verbose_name="学生姓名",max_length=16)
        gender_choices=((1,"男"),(2,"女"))
        gender=models.SmallIntegerField(verbose_name="性别",choices=gender_choices)
        education_choices=(
            (1,"重点大学"),
            (2,"普通本科"),
            (3,"独立院校"),
            (4,"民办本科"),
            (5,"大专"),
            (6,"民办专科"),
            (7,"高中"),
            (8,"其他")
        )
        education=models.IntegerField(verbose_name="学历",choices=education_choices,blank=True,null=True)
        graduation_school=models.CharField(verbose_name="毕业学校",max_length=64,blank=True,null=True)
        major=models.CharField(verbose_name="所学专业",max_length=64,blank=True,null=True)
        experience_choices=[
            (1,"在校生"),
            (2,"应届毕业"),
            (3,"半年以内"),
            (4,"半年至一年"),
            (5,"一年至三年"),
            (6,"三年至五年"),
            (7,"五年以上")
        ]
        experience=models.IntegerField(verbose_name="工作经验",blank=True,null=True,choices=experience_choices)
        work_status_choices=[
            (1,"在职"),
            (2,"无业")
        ]
        work_status=models.IntegerField(verbose_name="在职状态",choices=work_status_choices,default=1,blank=True,
                                        null=True)
        company=models.CharField(verbose_name="目前就职公司",max_length=64,blank=True,null=True)
        salary=models.CharField(verbose_name="当前薪资",max_length=64,blank=True,null=True)
        source_choices=[
            (1,"QQ群"),
            (2,"内部转介绍"),
            (3,"官方网站"),
            (4,"百度推广"),
            (5,"360推广"),
            (6,"搜狗推广"),
            (7,"搜腾讯课堂"),
            (8,"广点通"),
            (9,"高校宣讲"),
            (10,"渠道代理"),
            (11,"51cto"),
            (12,"智汇推"),
            (13,"网盟"),
            (14,"DSP"),
            (15,"SEO"),
            (16,"其他")
        ]
        source=models.SmallIntegerField(verbose_name="客户来源",choices=source_choices,default=1)
        referral_from=models.ForeignKey(
            to="self",
        blank=True,
        null=True,
        verbose_name="转介绍自学员",
        help_text="若此客户是转介绍自内部学员,请在此处选择内部学员姓名",
        related_name="internal_referral",
        on_delete=models.CASCADE
        )
        course=models.ManyToManyField(verbose_name="咨询课程",to="Course")
        status_choices=[
            (1,"已报名"),
            (2,"未报名")
        ]
        status=models.IntegerField(
            verbose_name="状态",
            choices=status_choices,
            default=2,
            help_text=u"选择客户此时的状态"
        )
        consultant=models.ForeignKey(verbose_name="课程顾问",to="UserInfo",related_name="consult",
                                     limit_choices_to={"depart_id":1001},on_delete=models.CASCADE)
        date=models.DateField(verbose_name="咨询日期",auto_now_add=True)
        recv_date=models.DateField(verbose_name="当前课程顾问的接单日期",null=True)
        last_consult_date=models.DateField(verbose_name="最后跟进日期")

        def  __str__(self):
            # return f"姓名:{self.name},QQ:{self.qq}"
            return self.name

class ConsultRecord(models.Model):#客户跟进记录
    customer=models.ForeignKey(verbose_name="所咨询客户",to="Customer",on_delete=models.CASCADE)
    consultant=models.ForeignKey(verbose_name="跟踪人",to="UserInfo",on_delete=models.CASCADE,limit_choices_to={"depart__in":[1001]})
    date=models.DateField(verbose_name="跟进日期",auto_now_add=True)
    note=models.TextField(verbose_name="跟进内容")

    def __str__(self):
        return f"{self.customer.name}:{self.consultant.name}"

class PaymentRecord(models.Model):#缴费记录
    customer=models.ForeignKey(to="Customer",verbose_name="客户",on_delete=models.CASCADE)
    class_list=models.ForeignKey(verbose_name="班级",to="ClassList",blank=True,null=True,on_delete=models.CASCADE)
    pay_type_choices=[
        (1,"订金/报名费"),
        (2,"学费"),
        (3,"转班"),
        (4,"退学"),
        (5,"退款"),
    ]
    pay_type=models.IntegerField(verbose_name="费用类型",choices=pay_type_choices,default=1)
    paid_fee=models.IntegerField(verbose_name="费用数额",default=0)
    turnover=models.IntegerField(verbose_name="成交金额",blank=True,null=True)
    quote=models.IntegerField(verbose_name="报价金额",blank=True,null=True)
    note=models.TextField(verbose_name="备注",blank=True,null=True)
    date=models.DateTimeField(verbose_name="交款日期",auto_now_add=True)
    consultant=models.ForeignKey(verbose_name="负责老师",to="UserInfo",help_text="谁签的单",on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.customer} {self.pay_type}"

class Student(models.Model):#学生表(已报名)
    customer=models.OneToOneField(verbose_name="客户信息",to="Customer",on_delete=models.CASCADE)
    username=models.CharField(verbose_name="用户名",max_length=32)
    password=models.CharField(verbose_name="密码",max_length=64)
    emergency_contract=models.CharField(verbose_name="紧急联系人",max_length=32,blank=True,null=True)
    class_list=models.ManyToManyField(verbose_name="已报班级",to="ClassList",blank=True)
    company=models.CharField(verbose_name="公司",max_length=128,blank=True,null=True)
    location=models.CharField(verbose_name="所在区域",max_length=64,blank=True,null=True)
    position=models.CharField(verbose_name="岗位",max_length=64,blank=True,null=True)
    salary=models.IntegerField(verbose_name="薪资",blank=True,null=True)
    welfare=models.CharField(verbose_name="福利",max_length=256,blank=True,null=True)
    date=models.DateField(verbose_name="入职时间",help_text="格式:年-月-日",blank=True,null=True)
    memo=models.CharField(verbose_name="备注",max_length=256,blank=True,null=True)

    def __str__(self):
        return self.username

class CourseRecord(models.Model):#上课记录表
    class_obj=models.ForeignKey(verbose_name="班级",to="ClassList",on_delete=models.CASCADE)
    day_num=models.IntegerField(verbose_name="节次",help_text=u"此处填写第几节课或第几天课程")
    teacher=models.ForeignKey(verbose_name="讲师",to='UserInfo',limit_choices_to={"depart__in":[1002,1005]},on_delete=models.CASCADE)
    date=models.DateField(verbose_name="上课日期",auto_now_add=True)
    course_title=models.CharField(verbose_name="本节课程标题",max_length=64,blank=True,null=True)
    course_memo=models.TextField(verbose_name="本节课程内容概要",blank=True,null=True)
    has_homework=models.BooleanField(default=True,verbose_name="本节有作业")
    homework_title=models.CharField(verbose_name="本节作业标题",max_length=64,blank=True,null=True)
    homework_memo=models.TextField(verbose_name="作业描述",max_length=500,blank=True,null=True)
    exam=models.TextField(verbose_name="踩分点",max_length=300,blank=True,null=True)

    def __str__(self):
        return f"{self.class_obj} day{self.day_num}"

class StudyRecord(models.Model):#学生记录表
    course_record=models.ForeignKey(verbose_name="第几天课程",to="CourseRecord",on_delete=models.CASCADE)
    student=models.ForeignKey(verbose_name="学员",to="Student",on_delete=models.CASCADE)
    record_choices=(
        ("checked","已签到"),
        ("vacate","请假"),
        ("late","迟到"),
        ("noshow","缺勤"),
        ("leave_early","早退")
    )
    record=models.CharField(verbose_name="上课记录",choices=record_choices,default="checked",max_length=32)
    score_choices=(
        (100,"A+"),
        (90,"A"),
        (85,"B+"),
        (80,"B"),
        (70,"B-"),
        (60,"C+"),
        (50,"C"),
        (40,"C-"),
        (0,"D"),
        (-1,"N/A"),
        (-100,"COPY"),
    )
    score=models.IntegerField(verbose_name="本节成绩",choices=score_choices,default=-1)
    homework_note=models.CharField(verbose_name="作业评语",max_length=255,blank=True,null=True)
    note=models.CharField(verbose_name="备注",max_length=255,blank=True,null=True)
    homework=models.FileField(verbose_name="作业文件",blank=True,null=True,default=None)
    stu_memo=models.TextField(verbose_name="学员备注",blank=True,null=True)

stark/models.py
from django.db import models

# Create your models here.

stark/views.py
from django.shortcuts import render

# Create your views here.

stark/templates/add_view.html
{% extends 'base.html' %}

{% block con %}

    <h3>添加数据</h3>
{% include 'form.html' %}

<script>
    // +号保存以后数据直接显示在框里面
    function pop_response(pk,text,id) {
        var $option = $('<option>'); // 生成一个option标签
        $option.html(text); //<option>南京出版社</option>
        $option.val(pk);    //<option value='sadsadsa'>南京出版社</option>
        $option.attr('selected','selected');
        $('#'+id).append($option)
    }
</script>
{% endblock %}

stark/templates/edit_view.html
{% extends 'base.html' %}

{% block con %}
<h3>编辑数据</h3>
{% include 'form.html' %}

<script>
    // +号保存以后数据直接显示在框里面
    function pop_response(pk,text,id) {
        var $option = $('<option>'); // 生成一个option标签
        $option.html(text); //<option>南京出版社</option>
        $option.val(pk);    //<option value='sadsadsa'>南京出版社</option>
        $option.attr('selected','selected');
        $('#'+id).append($option)
    }
</script>
{% endblock %}

stark/templates/form.html
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="" method="post" novalidate>
            {% csrf_token %}
                {% for field in form %}
                    <div style="position: relative">
                        <label for="">{{ field.label }}</label>
                        {{ field }}<span class="error pull-right">{{ field.errors.0 }}</span>
                        {% if field.is_pop %}  {# 如果有自己定义这个属性 则有+号 #}
                            <a onclick="pop('{{ field.url }}')" style="position: absolute;right: -30px;top: 20px" ><span style="font-size: 28px">+</span></a>
                        {% endif %}

                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-default">提交</button>
            </form>
        </div>
    </div>
</div>
<script>
    function pop(url) {
        window.open(url,'','width=600,height=400,top=100,left=100')
    }

</script>

stark/templates/list_view.html
{% extends 'base.html' %}

{% block con %}
    <h3>查看列表</h3>
{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <a href="{{ add_url }}" class="btn btn-primary">添加数据</a>
            {#  如果你配置了搜索框就有显示 没有不显示 #}
            {% if showlist.config.search_fields %}
                <form action=""  class="pull-right">

                    <input type="text" name="q" value="{{ showlist.config.key_word }}"><button>提交</button>
                </form>
            {% endif %}



            <form action="" method="post">
                {% csrf_token %}
                <select name="action" id="" style="width: 200px;padding: 5px 8px;display: inline-block;margin: 5px 0px" >
                    <option value="">-------------------------</option>
                    {% for item in showlist.get_action_list %}
                        <option value="{{ item.name }}">{{ item.desc }}</option>
                    {% endfor %}

                </select><button type="submit" class="btn btn-default" style="margin-left: 5px;margin-top: -4px">Go</button>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    {% for item in showlist.get_header %}
                        <th>{{ item }}</th>
                    {% endfor %}

                </tr>
                </thead>
                <tbody>
                {% for data in showlist.get_body %}
                    <tr>
                        {% for item in data %}
                            <td>{{ item }}</td>
                        {% endfor %}

                    </tr>
                {% endfor %}


                </tbody>
            </table>
            <nav>
                <ul class="pagination">
                    {{ showlist.page.page_html|safe }}
                </ul>
            </nav>
                 </form>
        </div>
        <div class="col-md-3">
            {% if showlist.config.list_filter %}
                 <div class="filter">
                <h4 class="">Filter</h4>
                {% for filter_field,link_tags in showlist.get_filter_linktags.items %}
                    <div class="well">
                        <p>{{ filter_field.upper }}</p>
                        {% for tag in link_tags %}
                            <p>{{ tag|safe }}</p>
                        {% endfor %}

                    </div>
                {% endfor %}

            </div>
            {% endif %}

        </div>
    </div>
</div>


<script>
    $('#choice').click(function () {
        if ($(this).prop('checked')) {
            $('.item').prop('checked', true)
        }
        else {
            $('.item').prop('checked', false)
        }
    })

    $('.del').click(function () {
        var $id=$(this).attr("id");
        swal({
                title: "Are you sure?",
                text: "Your will not be able to recover this imaginary file!",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            },
            function () {
                // 向后端发送请求
                $.ajax({
                    url : '{{ del_url }}',
                    type : 'post',
                    data : {
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                        id:$id
                    },
                    success:function (data) {
                        swal("data!", "Your imaginary file has been deleted.", "success");
                        location.href=''
                    }

                });

            });
    })

</script>
{% endblock %}

stark/templates/mycustomer.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<h4>我的客户</h4>
<ul>
    {% for customer_distrbute in customer_distrbute_list %}
        <li>{{ customer_distrbute.customer }}-----{{ customer_distrbute.date }}------{{ customer_distrbute.get_status_display }}</li>
    {% endfor %}
    
</ul>

</body>
</html>

stark/templates/pop.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<script>

    window.opener.pop_response('{{ res.pk }}','{{ res.text }}','{{ res.pop_res_id }}');
    window.close()
</script>


</body>
</html>

stark/templates/public.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
</head>
<body>

<h3>公共客户</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>姓名</th>
                        <th>QQ</th>
                        <th>课程顾问</th>
                        <th>跟进详情</th>
                        <th>确认跟进</th>
                    </tr>
                </thead>
                <tbody>
                    {% for customer in customer_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.qq }}</td>
                            <td>{{ customer.consultant }}</td>
                            <td><a href="/stark/crm/consultrecord/?customer={{ customer.pk }}">跟进记录</a></td>
                            <td><a href="/stark/crm/customer/further/{{ customer.pk }}">确认跟进</a></td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>

stark/templates/score.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
</head>
<body>

<h3>录入成绩</h3>
<form action="" method="post">
{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>学生姓名</th>
                        <th>考勤</th>
                        <th>成绩</th>
                        <th>批语</th>
                    </tr>
                </thead>
                <tbody>
                    {% for Study_record in Study_record_list %}
                        <tr>
                            <td>{{ Study_record.student }}</td>
                            <td>{{ Study_record.get_record_display }}</td>
                            <td style="width: 150px">
                                <select name="score_{{ Study_record.pk }}" id="" class="form-control">
                                    {% for item in score_choices %}
                                        {% if Study_record.score == item.0 %}
                                            <option selected value="{{ item.0 }}">{{ item.1 }}</option>
                                        {% endif %}
                                        <option value="{{ item.0 }}">{{ item.1 }}</option>
                                    {% endfor %}

                                </select>
                            </td>
                            <td>

                                <textarea name="homework_note_{{ Study_record.pk }}" id="" cols="20" rows="5" class="form-control">{{ Study_record.homework_note }}</textarea>
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
            <input type="submit" class="btn btn-default pull-right" >
        </div>
    </div>
</div>
</form>
</body>
</html>

stark/templates/score_view.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <script src="/static/jquery-3.3.1.min.js"></script>
    <script src="/static/chart/highcharts.js"></script>
</head>
<body>

<h3>查看{{ student }}成绩</h3>

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>班级</th>
                    <th>班主任</th>
                    <th>任课老师</th>
                    <th>课程成绩</th>
                </tr>
                </thead>
                <tbody>
                {% for class in class_list %}
                    <tr>
                        <td>{{ class }}</td>
                        <td>{{ class.tutor }}</td>
                        <td>
                            {% for teacher in class.teachers.all %}
                                <span>{{ teacher }}</span>&nbsp;
                            {% endfor %}

                        </td>
                        <td>
                            <a class="check_chart" cid="{{ class.pk }}" sid="{{ student.pk }}"><span>查看成绩</span></a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>

        </div>
    </div>
</div>
<div id="container" style="width:400px;height:400px"></div>
<script>
    $('.check_chart').click(function () {
        $.ajax({
            url: '',
            type: 'get',
            data: {
                sid: $(this).attr('sid'),
                cid: $(this).attr('cid')
            },
            success: function (data) {
                var chart = Highcharts.chart('container', {
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: '查看成绩'
                    },
                    subtitle: {
                        text: '数据来源:不告诉你'
                    },
                    xAxis: {
                        type: 'category',
                        labels: {
                            rotation: -45  // 设置轴标签旋转角度
                        }
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: '分数'
                        }
                    },
                    legend: {
                        enabled: false
                    },
                    tooltip: {
                        pointFormat: '分数: <b>{point.y:.1f} </b>'
                    },
                    series: [{
                        name: '分数',
                        data: data,
                        dataLabels: {
                            enabled: true,
                            rotation: -90,
                            color: '#FFFFFF',
                            align: 'right',
                            format: '{point.y:.1f}', // :.1f 为保留 1 位小数
                            y: 10
                        }
                    }]
                });
            }
        })
    })
</script>
</body>
</html>